### ISSUE TITLE
feature request: frecency indicator per channel

### ISSUE THREAD

**Issue by sharethewisdom** [Dinger1112/BetterYouTubeSubs#26]
thank you for this well written add-on.

Some channels publish many videos at once (i.e. after a conference). Rather than filtering out all of the videos of such a channel, it could be useful to mark new videos that trend well per channel.

This poor oneliner should return an array of objects with views and channel name per video:

```js
[...document.querySelectorAll('ytd-channel-name')].map(e => { return { "views": e.parentElement?.parentElement?.querySelector('#metadata-line > span'), "channel": e.querySelector('a')?.innerText.toLowerCase()}})
```

A "trending" video, in my opinion, is one that is very recent and already has a relatively high number of views. Although I'm aware that there is a complicated view-count consensus system behind the worldwide Youtube delivery network, I still think it is a reliable indicator for picking out either click-bait or genuinely interesting talks.

**Comment by Dinger1112** [comment]
As much as i would also like to be able to filter on videos that are "trending," i don't think the subs page alone has enough information to parse to give sufficient results. Creating this feature, to the best of my knowledge, requires an implementation outside the scope of this project so unfortunately i'm gonna pass on adding this feature.
